### PR TITLE
New Brand Morph Logo

### PR DESCRIPTION
**Pull request by cibersheep**
As discussed [in the forum](https://forums.ubports.com/topic/4625/morph-icon-proposal/2) I propose this new icon for the Morph Browser.

imatge

imatge

imatge

### CODE REVIEW

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
The error on installation is this:

```
+ dh_install --fail-missing
dh_install: morph-browser missing files: usr/share/morph-browser/*.png
dh_install: usr/share/morph-browser/morph-browser.svg exists in debian/tmp but is not installed to anywhere
dh_install: missing files, aborting
```

You will also need to add the morph-browser.svg to https://github.com/ubports/morph-browser/blob/xenial/debian/morph-browser.install

**Comment by cibersheep** [comment]
Sorry about that. Modified. Do I need to keep the *.png?

**Comment by UniversalSuperBox** [comment]
No, having both should not be required.

**Comment by cibersheep** [comment]
I have added a splash screen. I need to _ubport-qa_ it

**Comment by cibersheep** [comment]
Icon and Splash

imatge imatge

**Comment by dobey** [comment]
I guess @balcy should have some input here. Do we want to merge this for OTA-14?

**Comment by balcy** [comment]
what do @UniversalSuperBox and @mariogrip think ?

**Comment by UniversalSuperBox** [comment]
Well, I sure like it. :)

**Comment by lutin11** [comment]
I feel Nostalgic http://www.ti99.com/exelvision/website/

**Comment by mateosalta** [comment]
I'm for it. It really pulls together the new brand of "Morph". with blue morpho butterfly, the wing in the icon is reminiscent of a arrow pointing the way. Also I like the usage of tanagrams.

**Comment by UniversalSuperBox** [comment]
This was a discussion-causing PR in a couple of places, so I think we'll save it until after OTA-14 is released.

**Review by UniversalSuperBox — APPROVED** [review]

**Comment by cibersheep** [comment]
Weeeeeeeeeeeeeee

**Pull request merged**
