### PR TITLE
add UriHandler to webcontainer

### LINKED ISSUE #295: Webapps do not open links from url dispatcher
Currently, when a webapp is made with a url-dispatcher file, the links are redirected to the app but the default page is loaded.

Expected behaviour:
the passed link should be opened, not the default page

As I cannot guarantee this is Morphs fault see this web app I made in case there is something I have configured wrong:
https://github.com/giiba/Github_UT

### PR DESCRIPTION
**Pull request by balcy**
fixes https://github.com/ubports/morph-browser/issues/295

### CODE REVIEW

**Comment by balcy** [comment]
hints for test:
- install https://github.com/balcy/Github_UT via clickable
- click on a github link in Dekko and confirm the message (github webapp is not running)
-> the github webapp should open with the link
- close and open the github webapp (default page ubports opens)
- click on a github link in Dekko
-> the page of the github webapp should change to the github link

**Comment by mauricioduarte01** [comment]
Thank you for this

**Comment by giiba** [comment]
I have been testing this, and if the app is closed it works as expected loading the correct page. If the webapp is running and I click a link elsewhere, the webapp is brought into focus but the link is not loaded.

**Comment by balcy** [comment]
hi, have you checked that /usr/share/morph-browser/webcontainer/webapp-container.qml does have the added content https://github.com/ubports/morph-browser/commit/fd92f234350636edce91f297afeff59718b0197a ? 

If not you can replace it with https://raw.githubusercontent.com/ubports/morph-browser/fd92f234350636edce91f297afeff59718b0197a/src/app/webcontainer/webapp-container.qml and restart the webapp

**Comment by giiba** [comment]
My mistake. Sometime between modifying the webapp and actually testing the fix I switched update channels.

The clicking links in others apps now properly opens the github app and redirects it to the correct page regardless of the app's state.

Thanks!

**Review by dobey — APPROVED** [review]
Looks ok.

**Pull request merged**
