### PR TITLE
Enable unit tests

### PR DESCRIPTION
**Pull request by balcy**
- enable unit tests (QML and C++)
- correct WebProcessMonitor
- fix HoveredUrlLabel
- fix "topsites not deleted" in PreviewManager

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
I've tried merging this with the current state of `xenial` and it has begun to fail... What would you like to do with this PR?

**Comment by balcy** [comment]
should I try to rebase it to xenial ? Did the merge fail, or the build ?

**Comment by UniversalSuperBox** [comment]
Yes, it should be rebased. Sorry for being unclear, the build failed.

**Comment by balcy** [comment]
ah ok maybe test cases failed, I'll look into it.

**Comment by balcy** [comment]
Recently the "New Tab" and "Done" buttons / the whole footer was removed from the bookmarks and history pages.
The corresponding test cases failed, which I have removed in https://github.com/ubports/morph-browser/tree/xenial_-_enabletestsrebase2

Is it better to file a new PR from the new branch, or rather make the adaption in this branch and then resolve the one remaining merge conflict with xenial ?

**Comment by UniversalSuperBox** [comment]
Superseded by https://github.com/ubports/morph-browser/pull/498

**Pull request closed without merging**
