### PR TITLE
Update browserapplication.cpp

### LINKED ISSUE #440: QtQuick Controls 2 Style isn't Suru
I saw that `QT_QUICK_CONTROLS_STYLE` is being set to `Suru` in the code however, it doesn't seem to take effect on QQC2 components. A sample I tried is `Menu` which looks like styled with the `Default` style.

Here's a sample screenshot. (Ignore the wrong orientation, it's another issue that seems to affect `Menu` :sweat_smile: )
image

### PR DESCRIPTION
**Pull request by balcy**
fixes https://github.com/ubports/morph-browser/issues/440
move setting of the suru style towards the top of the function

### CODE REVIEW

**Comment by balcy** [comment]
hint for test:

- open "Settings" from the main menu

the selection for the default zoom should look like this (the same shape with dark colors in dark mode):
image

it should NOT look like this:
image

**Comment by kugiigi** [comment]
Looks like `TabPreview` has to be updated for this.
It uses `SwipeDelegate` which has padding in `Suru`.
The fix is to set the following. Apparently, `padding: 0` isn't enough.
```
leftPadding: 0
rightPadding: 0
topPadding: 0
bottomPadding: 0
```

**Comment by balcy** [comment]
ok thanks for the hint!

**Comment by dano6** [comment]
Maybe we should define QT_QUICK_CONTROLS_STYLE=Suru systemwise in utouch, because currently Suru is not the default QQC2 theme.

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
