### PR TITLE
Enable plugins

### PR DESCRIPTION
**Pull request by mateosalta**
This pull enables support for plugins, with this a user can more easily add plugins such as flash or widevine to the browser.

### CODE REVIEW

**Comment by mateosalta** [comment]
Also note that plugins also need a launch flag, the only one that is recognized in its location without a flag is flash, if this is a concern we could have this as a settings option. But I think this is an imortant step towards flash or widevine(netflix)

**Comment by Flohack74** [comment]
IMHO Flash should be used by noone anymore these days ;)

**Comment by mateosalta** [comment]
True. there are still some hold-outs, and I like that we can make this a possibility. And a step towards setting up netflix.

(side note, on of my favorite sites uses flash http://homestarrunner.com/ and it would be really nice to add to the "iphone can't do that" list)

**Comment by NeoTheThird** [comment]
> IMHO Flash should be used by noone anymore these days ;)

Yeah, but we should still allow it. And making it easy to use widevine will be very interesting for many users!

@mariogrip review please.

**Comment by mariogrip** [comment]
Thanks :+1:

**Pull request merged**
