### PR TITLE
theme support for the tab list (Rectangle instead of BorderImage) and current zoom text

### LINKED ISSUE #142: Morph doesn't properly support system themes for tabs headers
- Device: Meizu Pro 5

- Channel: 16.04 Devel

- Build: 2019-01-24

**Steps to reproduce**
Go to UT Tweak Tool and select a theme different from the default "Ambiance" (either SuruDark or SuruGradient). 

**Expected behavior**
The Morph browser app is expected to get the theme appropriately for each piece of the window.

**Actual behavior**
Instead, the SuruDark theme causes the disappearance of the cross used to close each open tab (look at the attached picture for the sake of clarity).

screenshot20190119_112016290

### PR DESCRIPTION
**Pull request by balcy**
fixes https://github.com/ubports/morph-browser/issues/142

### CODE REVIEW

**Comment by myii** [comment]
@balcy Thanks for this.  After a discussion on Telegram, I went ahead and hacked these [directly onto my device](https://t.me/ubports_qa_team/11453).  The tab list is now displaying fine.  How can I test the current zoom text?

**Comment by balcy** [comment]
without the change with SuruDark "Current Zoom: 100%" (at the bottom of the zoom menu) was not visible.

**Comment by myii** [comment]
On Fri, 8 Feb 2019 05:04:17 -0800, Chris Clime wrote:
> without the change with SuruDark "Current Zoom: 100%" (at the 
> bottom of the zoom menu) was not visible. 
>

I can confirm that both are working fine with this fix, thanks.

-- 
Sent using Dekko from my Ubuntu device

**Review by dobey — APPROVED** [review]
Looks OK to me, though would be nice to have regression tests for all the QML (but seems to be lacking in browser in general).

**Pull request merged**
