### PR TITLE
Add theming support...

### PR DESCRIPTION
**Pull request by nfsprodriver**
... to keep everything readable after changing the UI theme. Feel free to optimize it!
You can switch your theme best way by using UT Tweak tool latest version.

### CODE REVIEW

**Comment by myii** [comment]
@nfsprodriver I've only started testing this but the improvement is undeniable.  The `SuruDark` experience is so much better.  Thanks for working on this.

**Comment by nfsprodriver** [comment]
Thank you @myii ! Well, if there's nothing to add/change from your side, I'd like to remove the WIP status and it's ready to get merged :)

**Comment by balcy** [comment]
thank you for adding the theme support, the only small change I would do (I'm using the default theme) is to use slightly other colors for the light grey. (e.g. bottom bar), to match the previous colors when possible.
First I thought maybe Qt.lighter() / Qt.darker() can be used, but maybe it is better to find equivalents in the theme.
(e.g. theme.normal.foreground / theme.normal.overlay for the #f6f6f6)
I try sending some small change tomorrow.

**Comment by nfsprodriver** [comment]
Okay, good point. As I did that work, I didn't have the color palette in range. But I think I'll have a look at the UI theme definitions. We may add a table of the color palette for both Ambiance and Suru to the docs.

**Comment by balcy** [comment]
looks fine now, just have found 2 little things (color of the menu / tab count) for which I've made a PR to this branch. 👍

**Review by balcy — DISMISSED** [review]

**Comment by myii** [comment]
@nfsprodriver @balcy Thanks for the ongoing work.  You're probably already aware of this; the tab count is now being displayed but with a strange outline.

Using the latest commit:

```bash
phablet@ubuntu-phablet:~$ dpkg -l | grep morph-browser
ii  morph-browser                                        0.24+ubports+0~20181230145317.5~1.gbp63ced9                  armhf        morph web browser
```

We've got:

screenshot20181230_171150211

**Comment by nfsprodriver** [comment]
Hm, on my N5 everything looks fine for both themes.

**Comment by myii** [comment]
@balcy Excellent, that's fixed now, thanks.

screenshot20181231_002525507

**Review by balcy — APPROVED** [review]

**Comment by balcy** [comment]
oops forgot to squash the PR (phone screen too small), hopefully next time.

**Comment by myii** [comment]
@nfsprodriver @balcy Spotted a little problem.  Don't think it's worth opening a new issue about, informing you both seems enough.

#### Switching tabs in portrait orientation

`Ambiance`:

screenshot20190102_144642407

`SuruDark`:

screenshot20190102_144045883

**Comment by balcy** [comment]
yes those are mentioned here: https://github.com/ubports/morph-browser/pull/134
Thank you for reporting it.
Also the "SuruGradient" theme has more problems (e.g url in address bar, contrasts in general).

**Pull request merged**
