### PR TITLE
tab look changes

### PR DESCRIPTION
**Pull request by mateosalta**
extend tab downward for full connected tab look (removes corner artifacts), remove tab outline for a more flat look and rely on tab shadow.

### CODE REVIEW

**Comment by mateosalta** [comment]
screenshot20201005_143809453
screenshot20201005_143549393

**Comment by UniversalSuperBox** [comment]
Hi @mateosalta, it appears that this change conflicts with some changes that have been made in the xenial branch. Could you update your branch?

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
I don't think the divider should be removed. If two pages have similar colors, there is no separation between them.

Tabs without divider

Whereas with the divider, the pages look separate from each other:

Tabs with divider

**Comment by mateosalta** [comment]
Oh, yes i can add that back in. I was trying to fix the slight drop shadow instead but was not having luck :) will focus on the tab part for this one

**Comment by mateosalta** [comment]
Awesome @UniversalSuperBox I have added the divider back, now this pr only changes the tab look, specifically: outline of tab, shape of the bottom of the tab extends downward so that it is more like a tab similar to the tabs in morph's wider view.
photo_2021-05-18_18-08-10
photo_2021-05-18_18-08-01

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
