### PR TITLE
Added searchengine MetaGer

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by balcy** [comment]
maybe we can use both https://metager.org (English) and https://metager.org/de (German)

**Comment by ghost** [comment]
Should I make a new file or a new request for both?

**Comment by balcy** [comment]
I'd say a new file for "Metager (en)", and the existing entry could be renamed to "Metager (de)" (with url https://metager.org/de)

**Comment by UniversalSuperBox** [comment]
Hello @beli3ver, will you be able to address the requested changes?

**Comment by UniversalSuperBox** [comment]
OP has closed their account

**Pull request closed without merging**
