### PR TITLE
Temporary Keyboard overlay fix

### PR DESCRIPTION
**Pull request by nfsprodriver**
... completely removing white space

### CODE REVIEW

**Comment by nfsprodriver** [comment]
#5

**Comment by NeoTheThird** [comment]
I'm wondering what the rationale for the rectangle was in the first place. It might be nice not to have it, if you want keyboard opacity, for example.

**Comment by NeoTheThird** [comment]
Ah!

> This file was originally part of the telephony application.
It is a workaround required to handle interaction with the OSK,
until the shell/WM takes care of that on behalf of the applications.

https://github.com/ubports/browser-ng/pull/15/files#diff-1c9bca71438f627d69c9571b4f62bd76R19

**Comment by NeoTheThird** [comment]
Isn't what we're seeing here that the shell is actually taking care of it, and the workaround is just messing everything up? If so, we can just remove this hack entirely, not just make it invisible :)

Pinging @mariogrip for Mir and Unity8 stuff.

**Comment by NeoTheThird** [comment]
Last edits (except from updating to newer libs) were 5 years ago.

**Comment by mariogrip** [comment]
Thanks :+1:

**Pull request merged**
