### PR TITLE
WIP: Build both next generation webbrowser and webapp-container in debian

### PR DESCRIPTION
**Pull request by nfsprodriver**
Description to be continued...

### CODE REVIEW

**Comment by nfsprodriver** [comment]
Yeah, you have a good point ;)

**Comment by Flohack74** [comment]
This error from CI:
```CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5WebEngineCore/Qt5WebEngineCoreConfig.cmake:101 (find_package):

  Could not find a configuration file for package "Qt5WebChannel" that is

  compatible with requested version "5.9.4".
```
should be fixed ;) maybe @mariogrip can take a look?

**Comment by nfsprodriver** [comment]
Well I'm not deep enough into this stuff yet so here the question: Would it make sense to contribute the browser-ng or is the plan the merge over the qtwebengine stuff to the native webbrowser-app branch? Because mardy is commiting to webbrowser-app so we have two parallel projects.
What's the plan for the future?

**Comment by nfsprodriver** [comment]
I'll close this PR since we now habe the xenial_-_morph branch...

**Pull request closed without merging**
