### PR TITLE
Restore custom user agents / add "always deny" for location access

### LINKED ISSUE #320: Site keep asking for location permission
there seems to be no way to permanently deny location permission to a given site.
ask mark 'remember choice' disables the Deny button.

for example tyr the following stie it will ask for location permission for every page:

[https://www.zap.co.il](https://www.zap.co.il) (Hebrew site, be ready for RTL orientation :))

Device: BQ Aqurias m10
SDK:16.04

### PR DESCRIPTION
**Pull request by balcy**
"Remember decision" for location access is available now for "Allow" and "Deny" (always deny was not possible before)
fixes https://github.com/ubports/morph-browser/issues/320

restore custom user agents (planned but not rolled out in https://github.com/ubports/morph-browser/pull/203), new QtWebEngine should handle them correctly (hopefully)

### CODE REVIEW

**Comment by balcy** [comment]
~~https://github.com/ubports/ubuntu-ui-toolkit/pull/82 needs to be merged first~~

**Comment by balcy** [comment]
https://github.com/ubports/ubuntu-ui-toolkit/pull/90 is required to avoid the crash of Qt Quick Controls Comboboxes

**Comment by balcy** [comment]
to test the custom user agents:
* navigate to https://zn6kx.codesandbox.io/ (user agent page 1) and save it to the favorites
* navigate to https://xcdqd.codesandbox.io/ (user agent page 2) and save it to the favorites
* for both pages the default (desktop or mobile) user agent should appear
* go to Settings -> Domain Specific Settings -> Custom User Agents
* click "+", type "u1" as name for the new user agent, and then click "OK"
* in the textarea type "dummy user agent 1 ..."
* click "+", type "u2" as name for the new user agent, and then click "OK"
* in the textarea type "dummy user agent 2 ..."
* go to Settings -> Domain Specific Settings
* click "+" and type "zn6kx.codesandbox.io" to add the domain (alternatively, change the zoom on the page as described above to add it automatically)
* check the box "custom user agent"
* click on "u1"
* click "+" and type "xcdqd.codesandbox.io" to add the domain (alternatively, change the zoom on the page as described above to add it automatically)
* check the box "custom user agent"
* click on "u2"
* navigate to https://zn6kx.codesandbox.io/
* you should see "dummy user agent 1 ..."
* navigate to https://xcdqd.codesandbox.io/
* you should see "dummy user agent 2 ..."

**Comment by balcy** [comment]
they had been removed from PR https://github.com/ubports/morph-browser/pull/203 due to unexpected behavior with the old QtWebEngine 5.11, which now hopefully are no longer present

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
The "TextArea on swipable item" thing on the "Custom User Agents" page seems particularly glitchy. I'm able to get it into a state where the text selection pips are not on top of the text area any more, I end up selecting text instead of tapping it, and some more fun behavior.

Additionally, using the keyboard's swipe features end up switching between the text boxes somehow... I wonder if focus is wrong, or if something else is going on?

I think we need a better way to create and edit custom user agents before we present this feature to people. This editable list with text areas on items with leading actions... doesn't work so well.

**Comment by balcy** [comment]
ok agreed. I've created a new dialog for editing the custom user agents instead.
For editing the custom user agents, there is now a trailing "edit" action in the user agents list.

**Comment by cibersheep** [comment]
Mmm... indeed is dominic specific settings are really difficult to navigate.
Have you got  a solution or do you want some help here?

**Comment by balcy** [comment]
I think this PR should only handle custom user agents, changes to the domain specific settings maybe with another one.
The 'edit custom user agent' mentioned by Dalton is now a dialog, any help to improve it is welcome.

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
