### PR TITLE
before saving the session before the last window is closed, call setFullscreen(false)

### PR DESCRIPTION
**Pull request by balcy**
fixes https://github.com/ubports/morph-browser/issues/202

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Hmm, I don't think this problem is exclusive to the browser. Really I think it's a bug deeper in the stack, and individual apps should not have to work around it just because they happen to use fullscreen.

I'll move the bug report to unity8 so it isn't your "problem". Sorry I didn't do that before.

**Comment by balcy** [comment]
ah ok, I thought the window state (that includes the fullscreen info) is saved and then later restored with that property.

**Comment by UniversalSuperBox** [comment]
I believe it is, but I also believe it *shouldn't*

**Comment by mariogrip** [comment]
Here is a global fix: https://github.com/ubports/unity8/pull/172

**Comment by UniversalSuperBox** [comment]
Superseded by https://github.com/ubports/unity8/pull/172

**Pull request closed without merging**
