### PR TITLE
enable find in page (search text)

### PR DESCRIPTION
**Pull request by balcy**
some context menu items (share, save, ...) not available for webapps
correct navigation requests for webapps (e.g. new view requested)
fixes for "select all" and copy link text action

### CODE REVIEW

**Comment by balcy** [comment]
up to now all onNewViewRequested for webapps were not working (they just were open in new tab requests for the browser)
I'm not sure how we should handle them in WebViewImplOxide.qml (webapps)
Should we block non-user initiated ones (popups) or open them always in the overlay ?

**Comment by balcy** [comment]
I think it might be good to open popups from the same domain in the overlay

**Comment by balcy** [comment]
@Xray1970 on the first start of sailbook I've seen that morph was opened with static.facebook.com links, could those be missing in the allowed list ?

**Comment by ghost** [comment]
> @Xray1970 on the first start of sailbook I've seen that morph was opened with static.facebook.com links, could those be missing in the allowed list ?

Hi, i need to check this. thanks for the info! I have check it but it seems the are not missing.

**Review by mariogrip — APPROVED** [review]
Awesome! LGTM :+1:

**Pull request merged**
