### PR TITLE
- fix empty favicons in the HistoryModel

### PR DESCRIPTION
**Pull request by balcy**
- error page only is cleared if document element exists

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Does this fix a specific issue or behavior?

**Comment by balcy** [comment]
yes for the recent "favicon" PR the icons for the HistoryModel have not always been cached correctly. (The database contained empty entries)
with this patch it was reliable for me.

**Comment by UniversalSuperBox** [comment]
How about the documentElement change, then? Does this fix the flickering error page?

**Comment by balcy** [comment]
no it doesn't, but for any error page that does not have a document element, the java script command cannot work.
For the flickering I rather plan to allow custom schemes generally in QtWebEngine, but ask the user when a custom URL is used for the first time for a domain (which has to be confirmed by the user, see https://github.com/ubports/morph-browser/issues/154)

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
