### PR TITLE
implement session history when long pressing on "back" button

### PR DESCRIPTION
**Pull request by lduboeuf**
screenshot20201223_163357687

### CODE REVIEW

**Comment by kugiigi** [comment]
I was supposed to work on this but I got side tracked with my other idea :smile: 
Can you also implement this in the forward button and also support right click?
I have a personal goal before the Pro1 X are shipped, make desktop use case on UT a lot more usable and Morph is main recipe for that :grin:

**Comment by lduboeuf** [comment]
> I was supposed to work on this but I got side tracked with my other idea 😄

Oh ok, feel free to make it your own

> Can you also implement this in the forward button and also support right click?

ok for the forward button
Right click ?, what is it for ?

> I have a personal goal before the Pro1 X are shipped, make desktop use case on UT a lot more usable and Morph is main recipe for that 😁

Yes good example 👍

**Comment by kugiigi** [comment]
Right click is for desktop use. When the user uses keyboard and mouse. It's how desktop browsers work. If I want to contribute to this PR? How do I do that? Open a PR for your branch? Working for UT is my holiday vacation 😄

**Comment by lduboeuf** [comment]
> Right click is for desktop use. When the user uses keyboard and mouse. It's how desktop browsers works.

didn't know we can use the right click on desktop mode over the back and forward button, i personaly use the long press on desktop too

If I want to contribute to this PR? How do I do that? Open a PR for your branch? Working for UT is my holiday vacation 😄

Humm, i don't think you can add commits on my branch vut maybe you can create your own and i will close that one

**Comment by mateosalta** [comment]
nice idea! I would go have it take up more space on the screen though, say about 3/4ths the screen on mobile portrait.

**Comment by lduboeuf** [comment]
closed in favor of #444

**Pull request closed without merging**
