### PR TITLE
add userscript ability, hide scrollbar

### PR DESCRIPTION
**Pull request by mateosalta**
This pull enables support for userscripts, includes an initial userscript that removes the qtwebengine built-in scrollbars that are controlled by css.

Todo: theme scrollbar like system scrollbars

### CODE REVIEW

**Comment by mateosalta** [comment]
Hm, didn't seem to build, is it because I added a file?

**Comment by mateosalta** [comment]
does the master branch build?

**Comment by UniversalSuperBox** [comment]
The build is currently broken on master

**Comment by mariogrip** [comment]
Could you rebase this to xenial_-_morph using the morph library?

**Comment by mateosalta** [comment]
Ah, cool ill take a look, I wasn't able to build the last one, so I was just changing things in the click then diff back master

**Pull request closed without merging**
